import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const SinglePostPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="flex border-b p-4">
          Post View
        </div>
      </main>
    </>
  );
};

export default SinglePostPage;