name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DATABASE_URL: "mysql://aecrvqw74xbguv4ccvsq:pscale_pw_BK2OJLvQFo6bby7UILc4EtfG1SdS1V6LUmh4ySekJ55@aws.connect.psdb.cloud/chirp-db?sslaccept=strict"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint
